### Working with JSON files

In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
#using url
pd.read_json() # just pass the url inside the brackets

TypeError: read_json() missing 1 required positional argument: 'path_or_buf'

### Working with SQL

In [6]:
pip install sqlalchemy psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.12-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 234.8 kB/s  0:00:20a 0:00:01m eta 0:00:02
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [7]:
from sqlalchemy import create_engine

In [26]:
from pathlib import Path
import pandas as pd


# 1. This converts '~' into something like '/Users/yourname' or '/home/yourname'
db_path = Path().home()/'Machine Learning/Data Gathering/rideshare.db'

# 2. Build the engine using 4 slashes for the absolute path
conn = create_engine(f'sqlite:////{db_path}')

# 3. Your query
query = "SELECT * FROM drivers"

# 4. Load into Pandas
try:
    df = pd.read_sql_query(query, con=conn)
    print("Data loaded perfectly!")
except Exception as e:
    print(f"Error: {e}")
finally:
    conn.dispose()

Data loaded perfectly!

In [27]:
df=pd.read_sql_query(query,con=conn)
df

,driver_id,user_id,vehicle_make,vehicle_model,vehicle_year,license_plate,rating,join_date,is_active
0,1,1781,Kia,Soul,2015,ZVJ-2140,4.10,2019-12-22,1
1,2,408,Hyundai,Tucson,2016,WLW-3906,4.21,2020-12-14,1
2,3,693,Hyundai,Sonata,2014,WEA-5140,3.81,2023-07-25,1
3,4,187,Nissan,Rogue,2021,KDE-9978,4.82,2020-01-11,1
4,5,1499,Ford,Fusion,2019,EKJ-8600,3.30,2023-07-15,0
...,...,...,...,...,...,...,...,...,...
395,396,571,Tesla,Cybertruck,2017,FBS-6111,4.94,2023-11-21,1
396,397,1658,Subaru,Legacy,2019,SMK-7631,4.56,2019-12-22,1
397,398,1764,Honda,CR-V,2020,VGV-6909,3.66,2022-09-18,1
398,399,446,Mazda,CX-9,2019,TZD-8159,4.68,2019-06-28,1
399,400,1933,Nissan,Pathfinder,2014,ZKG-1807,3.58,2022-05-18,1